name: CI Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  id-token: write
  contents: read

jobs:
  dotnet-docker:
    uses: edsonbraz/hello-world/.github/workflows/dotnet-docker.yml@main
    with:
      project_path: '.'
      dotnet_version: '9.0.x'
      docker_build_context: '.'
      dockerfile_path: './HelloWorld.API/Dockerfile'
      container_registry: 'ip5acr02.azurecr.io'
      image_name: 'helloworld-api'
    
